CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL,
	username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    
);


CREATE TABLE libri (
	id INT NONT NULL PRIMARY KEY AUTO_INCREMENT,
	titolo VARCHAR(30) NOT NULL,
	autore_cognome VARCHAR(30) NOT NULL,
	autore_nome VARCHAR(30) NULL NULL,
	anno VARCHAR(4) NOT NULL,
	pagine VARCHAR(4) NULL NULL,
	genere VARCHAR(50) NULL NULL,
	data_inserimento DATETIME NOT NULL CURRENT_TIMESTAMP
);